@basicShoppingCartMicroservice_HostAddress = http://localhost:5188

GET {{basicShoppingCartMicroservice_HostAddress}}/shopping-cart/123
Accept: application/json

###

GET {{basicShoppingCartMicroservice_HostAddress}}/shopping-cart/
Accept: application/json

###

POST {{basicShoppingCartMicroservice_HostAddress}}/shopping-cart/123/items
Content-Type: application/json

[1,2]

###

DELETE {{basicShoppingCartMicroservice_HostAddress}}/shopping-cart/123/items
Content-Type: application/json

[1,2]