@basicShoppingCartMicroservice_HostAddress = http://localhost:5188

GET {{basicShoppingCartMicroservice_HostAddress}}/shoppingcart/123
Accept: application/json

###

GET {{basicShoppingCartMicroservice_HostAddress}}/shoppingcart/
Accept: application/json